name: TEST-ENV-CLEANUP
# Remove test instance for closed pull requests

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: rlespinasse/github-slug-action@3.1.0
      - name: Set domain
        id: set-domain
        # Set test instance domain based on branch name slug
        run: |
          echo "::set-output name=domain::${{ env.GITHUB_HEAD_REF_SLUG_URL }}.dashboard.saleor.rocks"

